package org.mockmc.metaminer;

import org.apache.commons.io.FileUtils;
import org.bukkit.plugin.java.JavaPlugin;
import org.mockmc.metaminer.internal.MaterialDataGenerator;
import org.mockmc.metaminer.internal.potion.PotionDataGenerator;
import org.mockmc.metaminer.keyed.KeyedDataGenerator;
import org.mockmc.metaminer.keyed.RegistryKeyClassDataGenerator;
import org.mockmc.metaminer.recipes.RecipeDataGenerator;
import org.mockmc.metaminer.tags.TagDataGenerator;
import org.mockmc.metaminer.tests.BlockDataGenerator;
import org.mockmc.metaminer.tests.BlockStateGenerator;
import org.mockmc.metaminer.tests.ItemStackTestDataGenerator;
import org.mockmc.metaminer.translation.TranslationDataGenerator;
import org.mockmc.metaminer.world.WorldConfigurationGenerator;

import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;

public class MetaMiner extends JavaPlugin
{

	@Override
	public void onEnable()
	{
		this.getLogger().log(Level.INFO, "Generating data for MockMC");
		this.warmupRegistries();
		try
		{
			FileUtils.deleteDirectory(this.getDataFolder());
		}
		catch (IOException e)
		{
			throw new RuntimeException(e);
		}
		for (DataGenerator dataGenerator : getDataGenerators())
		{
			try
			{
				dataGenerator.generateData();
			}
			catch (IOException e)
			{
				e.printStackTrace();
				return;
			}
		}
		this.getLogger().log(Level.INFO, "Successfully generated data!");
		this.getLogger().log(Level.INFO, String.format("The files can be found at '%s'", this.getDataFolder().getPath()));
		this.getLogger().log(Level.INFO, "Copy these files with their respective directories over to the MockMC resources folder.");
		getServer().shutdown(); // We're done. So just call it quits.
	}

	private void warmupRegistries()
	{
		this.getLogger().log(Level.INFO, "Warming up registries...");
		long potionCount = org.bukkit.Registry.POTION.stream().count();
		if (potionCount == 0)
		{
			this.getLogger().log(Level.SEVERE, "Registry.POTION is empty! Generation may be incomplete.");
		}
		else
		{
			this.getLogger().log(Level.INFO, "Registry.POTION warmed up with {0} entries.", potionCount);
		}
	}

	private List<DataGenerator> getDataGenerators()
	{
		File testFolder = new File(this.getDataFolder(), "src/test/resources-autogenerated");
		File mainFolder = new File(this.getDataFolder(), "src/main/resources-autogenerated");
		return List.of(
				new BaseMockGenerator(this.getDataFolder()),
				// Sources
				new KeyedDataGenerator(mainFolder),
				new MaterialDataGenerator(mainFolder),
				new PotionDataGenerator(mainFolder),
				new RecipeDataGenerator(mainFolder),
				new RegistryKeyClassDataGenerator(mainFolder),
				new RegistryKeyClassDataGenerator(mainFolder),
				new TagDataGenerator(mainFolder),
				new TranslationDataGenerator(mainFolder),
				// Test
				new BlockStateGenerator(testFolder),
				new BlockDataGenerator(testFolder),
				new WorldConfigurationGenerator(testFolder),
				new ItemStackTestDataGenerator(testFolder)
		);
	}

}
