package org.mockmc.metaminer;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.util.List;

public class StandaloneRunner
{
	private static final Logger LOGGER = LoggerFactory.getLogger(StandaloneRunner.class);

	public static void main(String[] args) throws Exception
	{
		File dataFolder = new File(args[0]);
		dataFolder.mkdirs();

		File mainFolder = new File(dataFolder, "src/main/resources-autogenerated");
		File testFolder = new File(dataFolder, "src/test/resources-autogenerated");

		List<DataGenerator> generators = List.of(
				new BaseMockGenerator(dataFolder),
				new org.mockmc.metaminer.keyed.RegistryKeyClassDataGenerator(mainFolder),
				new org.mockmc.metaminer.keyed.KeyedDataGenerator(mainFolder),
				new org.mockmc.metaminer.internal.MaterialDataGenerator(mainFolder),
				new org.mockmc.metaminer.internal.potion.PotionDataGenerator(mainFolder),
				new org.mockmc.metaminer.recipes.RecipeDataGenerator(mainFolder),
				new org.mockmc.metaminer.tags.TagDataGenerator(mainFolder),
				new org.mockmc.metaminer.translation.TranslationDataGenerator(mainFolder),
				new BaseTestGenerator(dataFolder),
				new org.mockmc.metaminer.tests.BlockStateGenerator(testFolder),
				new org.mockmc.metaminer.tests.BlockDataGenerator(testFolder),
				new org.mockmc.metaminer.world.WorldConfigurationGenerator(testFolder),
				new org.mockmc.metaminer.tests.ItemStackTestDataGenerator(testFolder),
				new CoverageReportGenerator(dataFolder)
		);

		for (DataGenerator generator : generators)
		{
			LOGGER.info("Running {}", generator.getClass().getSimpleName());
			generator.generateData();
		}
		LOGGER.info("Generation complete!");
	}
}
